go_import_path: github.com/emccode/rexray

language: go

go:
  - 1.5.1

addons:
  apt:
    packages:
    - rpm

before_script:
  - source .build/dependencies.sh

script:
  - make build-all test rpm-all deb-all deploy-prep

notifications:
  - slack: $SLACK_BUILDS

before_deploy:
  - .build/bintray-decapitate.sh

deploy:
  - provider: bintray
    file: .build/bintray-stupid-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true) && ($TRAVIS_BRANCH = master || $IGNORE_BRANCH_CONDITION = true)

  - provider: bintray
    file: .build/bintray-staged-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ -rc[[:digit:]]+$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)

  - provider: bintray
    file: .build/bintray-stable-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)

cache:
  apt: true
  directories:
    - $HOME/.opt
