go_import_path: github.com/emccode/rexray

language: go

go:
  - 1.7

before_install:
  - git config --global 'url.https://gopkg.in/yaml.v1.insteadof' 'https://gopkg.in/yaml.v1/'
  - git config --global 'url.https://gopkg.in/yaml.v2.insteadof' 'https://gopkg.in/yaml.v2/'
  - git config --global 'url.https://gopkg.in/fsnotify.v1.insteadof' 'https://gopkg.in/fsnotify.v1/'
  - git config --global 'url.https://github.com/.insteadof' 'git://github.com/'
  - git config --global 'url.https://github.com/.insteadof' 'git@github.com:'
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover
  - make deps

script:
  - make gometalinter-all
  - make -j build-libstorage
  - env GOOS=linux  GOARCH=amd64 make -j build
  - env GOOS=darwin GOARCH=amd64 make -j build
  - make -j test

after_success:
  - make -j cover
  - make tgz
  - make rpm
  - make deb
  - make bintray
  - ls -al

deploy:
  - provider: bintray
    file: bintray-unstable.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true) && ($TRAVIS_BRANCH = master || $IGNORE_BRANCH_CONDITION = true)

  - provider: bintray
    file: bintray-staged.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ -rc[[:digit:]]+$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)

  - provider: bintray
    file: bintray-stable.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)

cache:
  apt: true
  directories:
  - $HOME/.opt

addons:
  apt:
    packages:
    - rpm
