language: go

go:
  - 1.5.1

addons:
  apt:
    packages:
    - cpio
    - debhelper
    - dpkg-dev
    - make
    - perl
    - rpm
    - fakeroot

before_script:
  - source install_build_deps.sh

script:
  - make build-all test rpm-all deb-all deploy-prep

notifications:
  - slack: $SLACK_BUILDS

before_deploy: 
  - ./.bintray-decapitate.sh

deploy:
  - provider: bintray
    file: .bintray-stupid-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true) && ($TRAVIS_BRANCH = master || $IGNORE_BRANCH_CONDITION = true)

  - provider: bintray
    file: .bintray-staged-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ -rc[[:digit:]]+$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)

  - provider: bintray
    file: .bintray-stable-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]$ && ($TRAVIS_REPO_SLUG = 'emccode/rexray' || $IGNORE_REPO_SLUG_CONDITION = true)

cache:
  apt: true
  directories:
    - $GOPATH/pkg
    - $HOME/.opt