site_name: REX-Ray
site_url: https://github.com/emccode/rexray
repo_url: https://github.com/emccode/rexray.git
docs_dir: .docs
site_dir: .site
theme_dir: .docs/.themes/yeti
site_favicon: favicon.png

pages:
- Home: index.md
- User Guide:
    - Installation: user-guide/installation.md
    - Configuration: user-guide/config.md
    - 'Amazon EC2': user-guide/ec2.md
    - Google Compute Engine: user-guide/gce.md
    - Isilon: user-guide/isilon.md
    - OpenStack: user-guide/openstack.md
    - Rackspace: user-guide/rackspace.md
    - ScaleIO: user-guide/scaleio.md
    - VMAX: user-guide/vmax.md
    - XtremIO: user-guide/xtremio.md
    - Docker: user-guide/docker.md
    - Mesos: user-guide/mesos.md
- Developers Guide:
    - Project Guidelines: dev-guide/project-guidelines.md
    - Build Reference: dev-guide/build-reference.md
    - Release Process: dev-guide/release-process.md
- About:
    - Contributing: about/contributing.md
    - License: about/license.md
    - Release Notes: about/release-notes.md
